name: Build & Push Docker Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" |
          docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Buildx
        run: docker buildx inspect --bootstrap || docker buildx create --use

      - name: Build and Push Primary Docker Image
        run: |
          docker buildx build \
            --build-arg CACHE_BUSTER=$(date +%s) \
            --platform linux/amd64,linux/arm64 \
            --tag katomyomachia/engr-131-jhub:latest \
            -f Dockerfile \
            --push .

      - name: Build and Push Exams Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag katomyomachia/engr-131-jhub-exams:latest \
            -f exams.Dockerfile \
            --push .
