name: Update Helm Chart

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run script to update Helm chart
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID_EXAMS: ${{ secrets.CLIENT_ID_EXAMS }}
          CLIENT_SECRET_EXAMS: ${{ secrets.CLIENT_SECRET_EXAMS }}
        run: ./deploy.sh
